//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FigmaScience.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FigmaScience
    {
        public int ID { get; set; }
        public Nullable<int> IDLessons { get; set; }
        public Nullable<int> IDTestResults { get; set; }
        public Nullable<int> IDTests { get; set; }
        public Nullable<int> IDUsers { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual TestResults TestResults { get; set; }
        public virtual Tests Tests { get; set; }
        public virtual Users Users { get; set; }
    }
}
