//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FigmaScience.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FigmaScienceEntities1 : DbContext
    {
        public FigmaScienceEntities1()
            : base("name=FigmaScienceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FigmaScience> FigmaScience { get; set; }
        public DbSet<Lessons> Lessons { get; set; }
        public DbSet<TestResults> TestResults { get; set; }
        public DbSet<Tests> Tests { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
