//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FigmaScience.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public Lessons()
        {
            this.FigmaScience = new HashSet<FigmaScience>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string HyperLink { get; set; }
    
        public virtual ICollection<FigmaScience> FigmaScience { get; set; }
    }
}
