//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FigmaScience.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.FigmaScience = new HashSet<FigmaScience>();
            this.TestResults = new HashSet<TestResults>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<FigmaScience> FigmaScience { get; set; }
        public virtual ICollection<TestResults> TestResults { get; set; }
    }
}
